### ISSUE TITLE
Demo Data

### ISSUE THREAD

**Issue by clcessexuk** [Eurotimmy/unraid-templates#5]
Hi, this docker is excellent and worked for me without a hitch. My issue is the demo data. No matter how I set it up it installs the demo. Do you know of a way around this or could you create a  version without it?

Thank you, Regards

**Comment by Eurotimmy** [comment]
Hi @clcessexuk, thank you for the question. 

This could be tried on a fresh install (need an empty DB) the first time you spin up the Odoo container so you may need to delete your existing DB from Postgres before trying this. 

I believe you can use this argument in "PostArgs" instead of my default one, but YMMV. 

"-i base --without-demo=all --stop-after-init"

... the above arguments would replace the "-i base" argument and *should* initialise Odoo17, without any demo data and then immediately stop the server. 

At that point you'll need to clear / empty the PostArgs field in the "Edit" menu on the Odoo17 Docker template, then restart the Docker container to see if you got the right outcome. 

Please give it a try if you like and let me know how you go?

**Comment by clcessexuk** [comment]
@Eurotimmy Worked Perfect. Thank you.

**Comment by Eurotimmy** [comment]
Great @clcessexuk !
I should've added that putting the option "without_demo = all" in your odoo.conf file will achieve the same. 

I'll update the README and support text to include these options. 

Thank you.

**Comment by Eurotimmy** [comment]
Updated the repo with better 'README' instructions
Added the option in odoo.conf file as well
